
scan_timeout = 30
command_timeout = 500
add_newline = true

format = "$all"

[character]
success_symbol="[➜](bold green)"
error_symbol="[✗](bold red)"

[battery]
disabled = false

[package]
disabled = true

